### ISSUE TITLE
Help with integration and contribution

### ISSUE THREAD

**Issue by prithsharma** [Kennytian/react-native-instabug#1]
Thanks a lot for bootstrapping this repo. :+1: 

Since you say you can't work on this anymore, I wanted to see if I can take it forward.
Can you please give a little more information about what you mean when you say 'Android 50% done'? It would help if you can give a general overview of code structure.

**Comment by Kennytian** [comment]
Android can be work now, but only two features(report bug  and report feedback). Welcome you join us write this component!
