### ISSUE TITLE
Instabug initialisation crashes in lower Android versions - 4.4

### ISSUE THREAD

**Issue by prithsharma** [Kennytian/react-native-instabug#9]
Probably this is about the instabug package but I couldn't find any issue about this elsewhere. Any ideas?

```
E/AndroidRuntime( 2755): java.lang.NoClassDefFoundError: rx.plugins.RxJavaPlugins
E/AndroidRuntime( 2755):    at rx.Observable.<clinit>(Observable.java:64)
E/AndroidRuntime( 2755):    at com.instabug.library.e.a.a(NetworkManager.java:60)
E/AndroidRuntime( 2755):    at com.instabug.library.e.a.f.a(SessionService.java:75)
E/AndroidRuntime( 2755):    at com.instabug.library.InstabugSessionUploaderService.c(InstabugSessionUploaderService.java:29)
E/AndroidRuntime( 2755):    at com.instabug.library.InstabugSessionUploaderService.b(InstabugSessionUploaderService.java:21)
E/AndroidRuntime( 2755):    at com.instabug.library.g.onHandleIntent(InstabugBackgroundService.java:32)
E/AndroidRuntime( 2755):    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime( 2755):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2755):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2755):    at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by Kennytian** [comment]
Try to change compile 'com.instabug.library:instabug:2+' code, maybe can resolve this crash.

**Comment by prithsharma** [comment]
Do you mean use some other version instead of the latest - 2.6.2 ?
I tried but that also doesn't seem to work. 
Are you able to get the example running in an Android 4.4 emulator?

**Comment by Kennytian** [comment]
@prithsharma   http://stackoverflow.com/questions/37619596/rxjava-noclassdeffounderror-rx-plugins-rxjavaplugins-on-api-16

adding compile 'io.reactivex:rxjava:1.0.16' to gradle fixes the problem
https://github.com/realm/realm-java/issues/1963

**Comment by Kennytian** [comment]
adding compile 'io.reactivex:rxjava:1.0.16' to gradle fixes the problem

https://github.com/realm/realm-java/issues/1963

**Comment by prithsharma** [comment]
:+1:  Although just adding that line didn't solve my problem, I think the issue was something about multidex support in lower Android versions(as the SO answer suggests).
The changes in addition to `multiDexEnabled true` in gradle's `defaultConfig` that solved it for me were:
- add `compile 'com.android.support:multidex:1.0.1'` in gradle dependencies to support multidex
- make `MainApplication` class in `MainApplication.java` to extend `MultiDexApplication` instead of `Application`

Thank you for the reply. Closing the issue.

**Comment by Kennytian** [comment]
Good job, invite you to maintain this project continue and let more people using it  💯
